# Generated by Django 5.2.8 on 2025-12-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmate', '0003_alter_cart_items_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
    ]
